### ISSUE TITLE
Float support for math.pow, missing exp and log instructions

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#113]
I was writing some audio synthesis code, and porting over some filter code I had written a while back. Unfortunately, the said filter relies on the `math.pow(x,y)` function accepting floating-point values, and right now we only support integers. I would like to fix that gap.

I think a good solution, for now, may be to expose the C `log(x)` and `exp(x)` functions through new `log_f32` and `log_f32` instructions, and use those to implement support in `math.pow(x,y)`, at least for positive floating-point values. We can throw an exception for negative floating-point exponents or bases. If you're willing, you can try to support the whole range of possible values, but some care has to be taken in determining which values should throw exceptions, and which ones should produce NaN as output.

To implement the new instructions, you should look in `vm/interp.cpp`. The math library code is in `plush/math.pls`. Tests should go into `tests/plush/math.pls`.

Comments and feedback welcome. Note that this is needed relatively soon (so I can continue writing my code! :D).

**Comment by bigs** [comment]
i'm probably down to do this tonight!

**Comment by maximecb** [comment]
@bigs Do it! :+1:

**Comment by maximecb** [comment]
@bigs Any chance to look at this? I ran into another place where pow of floats is needed.

**Comment by bigs** [comment]
@maximecb yeah i can knock this out! a question: how do you feel about adding [pow](http://www.cplusplus.com/reference/cmath/pow/) as a primitive and using that as well?

**Comment by maximecb** [comment]
@bigs The problem is that pow has many restrictions on the values it can take as input. An exception should be thrown if negative integers are passed as exponent, for example. Though I suppose we have to deal with these either way.

So, yes, we can add pow as a primitive, but you can't just directly call it. You still have to be careful in checking for invalid inputs. Also note that 2^infinity, for example, is a valid input (the result is +infinity).

**Comment by bigs** [comment]
@maximecb cool, sounds good!

**Comment by bigs** [comment]
@maximecb hmmm any reason why i'd be getting 

```
Assertion failed: (val.isFloat32()), function popFloat32, file vm/interp.cpp, line 300.
```

even though i'm guarding in plush with

```
if (typeof base == "float32" && typeof exp == "float32")
{
    return $pow_f32(base, exp);
}
```

(just as a test of the op)

**Comment by maximecb** [comment]
@bigs Are you sure this is happening in your implementation of the pow op? I suggest simplifying the test case as much as possible. If the problem persists, can you paste your whole test code?

**Comment by bigs** [comment]
yeah, it's actually reaching my pow op in the vm. i believe it has to do with the arity, as my exp/log operators work well. i'll push up a WIP branch for review in a sec.

**Comment by maximecb** [comment]
@bigs Alright. With the pow function, I was able to get my music code working :D

Check out: `./zeta examples/music.pls`

Need to have run `./configure --with-sdl2`

**Comment by bigs** [comment]
yaaaaaaas. once i get a little further a long i'll push up some of the music stuff i'm doing in haskell! constraint programming + combinators = fun sequencer. almost at a place where enough pieces are in place...

on the zeta front, i'd love to take on something a little more substantial. any thoughts?

**Comment by maximecb** [comment]
There are these two issues: https://github.com/zetavm/zetavm/issues/111, https://github.com/zetavm/zetavm/issues/96

I would also like to eventually have a core/midi API. I particularly care about MIDI input, because I would like to be able to interface with MIDI controllers. This is tricky because the APIs for Linux, Mac and Windows are different. There are some libraries out there that try to bridge the three, but I don't know how well-maintained and supported there are. I think rtmidi is probably the best developed one.

**Comment by bigs** [comment]
ahhhhhh amazing. i highly recommend rtmidi! i've just made bindings for it in haskell in fact (have a few things i'd like to clean up w/ the callback mechanism but will be OSS soon). i'd be happy to take that on. rtmidi is great b/c it's platform independent, maintained, and supports each OS's virtual midi bus so you have maximal reach!

**Comment by maximecb** [comment]
If you want to work on the `core/midi` API, I would suggest looking at the way other core packages are implemented in `vm/runtime.cpp`. Then you could open an issue and submit a proposal. The key thing is that I want to keep all of these APIs as minimalistic and simple as possible. It's very important to me to insulate the internals of Zeta from the specific design of external libraries. If at some point rtmidi stops being maintained, I want to be able to keep using the same internal API and implement it on top of a new library instead, without too much difficulty.

For inspiration, I will say that I've played a tiny bit with the Python rtmidi bindings, and found that pleasant to use. We can also start with MIDI input only, and add output support later. I might actually prefer that because we can polish this API properly before adding more to ZetaVM.
