### ISSUE TITLE
Core dump seen on 32 bit machine

### ISSUE THREAD

**Issue by noundlas** [zetavm/zetavm#116]
Assertion seen while running `Zeta` 
Below is the stack trace for `./zeta  --test`
```
(gdb) r --test
Breakpoint 2, testRuntime () at vm/runtime.cpp:763
763 {
(gdb)
764 std::cout << "runtime tests" << std::endl;
(gdb)
764 std::cout << "runtime tests" << std::endl;
(gdb)
runtime tests
789 assert (arr.getElem(0) == Value::ZERO);
(gdb)
792 auto arr2 = Array(0);
(gdb)
793 assert (arr2.length() == 0);
(gdb)
794 arr2.push(Value::ONE);
(gdb)
zeta: vm/runtime.cpp:120: uint8_t* Wrapper::getNextPtr(refptr, refptr): Assertion `nextPtr != nullptr' failed.
Program received signal SIGABRT, Aborted.
0xb7fdd428 in __kernel_vsyscall ()
(gdb) p Value::ONE
$1 = {word = {float32 = 1.40129846e-45, int64 = 1, int32 = 1, int8 = 1 '\001', ptr = 0x1 <error: Cannot access memory at address 0x1>},
tag = 2 '\002', static ZERO = {word = {float32 = 0, int64 = 0, int32 = 0, int8 = 0 '\000', ptr = 0x0}, tag = 2 '\002',
```

Machine and compiler details are below
```
universe@universe-Lenovo-G50-80:~/zetavm$ uname -a
Linux universe-Lenovo-G50-80 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:56:31 UTC 2017 i686 i686 i686 GNU/Linux
universe@universe-Lenovo-G50-80:~/zetavm$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.3' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
```

**Comment by noundlas** [comment]
Let me play around with it. I think I could be able to figure it out what could be going wrong.

**Comment by noundlas** [comment]
Issue is found.

During `Array::Push` 
We are trying to do
```
292	        setNextPtr(rootObjPtr, newArr.getObjPtr());  
293         assert (getObjPtr() != ptr);
```
`setNextPtr` is assigning nextPtr and it is getting overwritten while setting the HEADER_MSK_NEXT
```
(gdb) s
Wrapper::setNextPtr (this=0xbfffeb3c, obj=0x80af190 "\b", nextPtr=0x80af258 "\b") at vm/runtime.cpp:102
102	    auto header = *(uint64_t*)obj;
(gdb) n
106	    *(refptr*)(obj + OBJ_OF_NEXT) = nextPtr;
(gdb) 
109	    *(uint64_t*)(obj) = header | HEADER_MSK_NEXT;
(gdb) p nextPtr
$62 = (refptr) 0x80af258 "\b"
(gdb) p *(refptr*)(obj + 4) 
$63 = (refptr) 0x80af258 "\b"
(gdb) p (refptr*)(obj + 4) 
$64 = (refptr *) 0x80af194
(gdb) p *(refptr *) 0x80af194
$65 = (refptr) 0x80af258 "\b"
(gdb) n
110	}
(gdb) p *(refptr *) 0x80af194
$66 = (refptr) 0x0
(gdb) 
 ```

**Comment by maximecb** [comment]
Good find, thank you for taking the time to look through this. I apologize for the slow response. Currently on a trip in Europe and only getting back Tuesday. Are you able to suggest a fix?

**Comment by noundlas** [comment]
@maximecb oh cool.. Have a good time in Europe. Let me check the assembly code. After that I should be able to comment on the fix.

**Comment by krypt-n** [comment]
How'd you get the regex stuff to work on gcc 4.8? On the version I just built I can't get past `packages.cpp:882`.

**Comment by krypt-n** [comment]
Ah, it's not the gcc version, this issue is caused by your target being 32-bit. If `sizeof(intptr_t) < sizeof(uint64_t)`, `setNextPtr` will overwrite half of the nextPtr.

**Comment by noundlas** [comment]
@krypt-n Yes. Even I felt the same.. But i have failed to reproduce this issue in c code snippet.. so just confused little. Had to understand why this issue is seen only with zetavm.

Here is my analysis and update on this issue.
it seems to be difference between uint32 and uint64. I have used uint32 instead of uint64 in setNextPtr.. i was seeing another issue later in execCode method while loading ex_fibonacci.zim..

The opCode is was coming as 2059 which is not part of the depth of opCode enum.

Had to start understand the loading of zin files and execution of opCodes steps..

**Comment by noundlas** [comment]
Even i am seeing issue with regex stuff. I took this issue first later we can have look into the others.

**Comment by krypt-n** [comment]
>  it seems to be difference between uint32 and uint64. I have used uint32 instead of uint64 in setNextPtr.. i was seeing another issue later in execCode method while loading ex_fibonacci.zim..

The fix that would work on both 32 and 64 bit platforms is to replace `uint64_t` with `intptr_t`, since `HEADER_SIZE` and `OBJ_OF_NEXT` are equal to `sizeof(intptr_t)`

Furthermore I can reproduce your second issue. The codegen for the `import` opcode writes a `refptr` and a `Tag` after the opcode into the code buffer. However, the actual implementation expects a `Word` and a `Tag`. This leads to the problem you observed when `sizeof(refptr) < sizeof(Word)`.

Do you want to make fixes for the issues or do I?

**Comment by noundlas** [comment]
Wow it's cool... Yes go ahead.. if you have the fixes ready..

**Comment by noundlas** [comment]
@krypt-n aren't you seeing issue like isObject(); for Opcode GET_LOCAL_IMM for popObject. While loading Fibonacci.zim

I see that push happened for type of TAG_HOSTFN  and while trying to pop the value, it has been seen as type TAG_HOSTFN where as it expects TAG_OBJECT aa it is popObject method.

**Comment by krypt-n** [comment]
No, I'm not seing any other issues when running the testset with the fixes from the PR. Which fibonacci.zim do you mean?

**Comment by noundlas** [comment]
If you run `make test` it executes `zeta --test` which in turn loads ex_fibonacci.zim.. anyways let me debug it further.. i am not seeing these issues on 64 bit machine.. could be related to 32 bit

**Comment by noundlas** [comment]
@krypt-n its cool now. Not sure what was the issue and how it got addressed too. I have done `./configure` once again and gave clean build. Things started working. with your patch on :)

**Comment by maximecb** [comment]
Schweet! So now we'll have Mac, Linux and Windows support in both 32 and 64-bit.

@krypt-n Do you have time to fix the travis config for the PR?
