### ISSUE TITLE
Dynamic parser generation

### ISSUE THREAD

**Issue by ponyatov** [zetavm/zetavm#123]
Does any parser design functionality exists in current implementation?

Maybe **metaprogramming should be the main feature** for programming languages Olympus seizure by Zeta core. I see a lot of abilities already exists in code samples (_bytecode manipulation in symbolic form_ are roaring). To do this language core must support **dynamic lexer/parser** creation and **modification in runtime** to be able to mimic any syntax for random DSL, **and grammar inheritance** should be supported.

**Comment by maximecb** [comment]
Yeah that was the idea.
