### ISSUE TITLE
Implementation of a LISP-like language front-end

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#2]
Title says it all. I would like to implement a lisp-like language front-end for Zeta. I was thinking that the LISP dialect supported could be named "miniLISP". Another possibility would be to go for full-on scheme support.

**Comment by meadori** [comment]
I am up for implementing Scheme.  Say, R7RS?

**Comment by maximecb** [comment]
If you're implementing it, you get to pick the one you want 👍 

Do you need guidance as to how to proceed? There are at least two ways of going about it.

1. You can write your own scheme to zeta-image compiler which outputs textual IR. If you go this route, I would prefer you write the compiler in C, C++ or Python.

See the cplush C++ implementation:
https://github.com/maximecb/zetavm/tree/master/plush

2. Write a Scheme to Zeta IR compiler which runs inside Zeta. This is how the self-hosted Plush implementation works. It generates Zeta IR in memory. The downside of this approach is that Plush is currently the only language that runs on ZetaVM, and so you would have to write your compiler in this very barebones language.

See the parser.pls parser for an example:
https://github.com/maximecb/zetavm/blob/master/plush/parser.pls

**Comment by meadori** [comment]
Thanks for the tips!  I am quite comfortable with C++.   I would like to follow a similar path as Plush -- implement C++ and then self-host.  Self-hosting is always a great test for implementing languages.

I have been reading the existing Zeta code to get a feel for the style, but is there a style guide or coding standard anywhere?  Or a .clang-format for the C++ code would be great too.

**Comment by maximecb** [comment]
Awesome. Curious to see how it works out. Feel free to send pull requests often. I'd be really happy to have more code to test the VM.

There is no official style guide. I prefer curly braces on their own line and 4-wide soft tabs. I tend to use camelCase. Not too strict about style.

**Comment by maximecb** [comment]
@meadori Are you still working on this?

**Comment by meadori** [comment]
@maximecb I am.  I obviously haven't pushed much lately (the day job has been very busy).  I will get back into things this week.

**Comment by maximecb** [comment]
I hear you. Busy with my new job as well. Glad to hear you're still at it :)

**Comment by maximecb** [comment]
Hi there. I will be presenting Zeta at a conference next weekend, and would rather people see working language implementations when they check out the repo. Are you able to progress on this in the meantime? If not, I may close the issue and remove the associated code.

**Comment by meadori** [comment]
HI!  I do plan to continue with it (still haven't had many non-work cycles).  How much progress by next weekend?

**Comment by maximecb** [comment]
If you are still working on it I will leave it there. Do you think you
could have if and function calls by next  Saturday? Need enough
functionality to build useful examples.

Make sure to git pull before resuming work because I made some minor
changes to keep it working.

**Comment by meadori** [comment]
Functions calls and if support by next Saturday seems reasonable.  I think I can do that.  If I don't hit it for some reason, then we can pull things into a branch (or I will keep the implementation in my fork).

**Comment by maximecb** [comment]
Ok sounds good :)

**Comment by meadori** [comment]
I got the `if` work in, but I am still working on full function definition and application support.  It will be a couple more days.  I understand if you need to pull the implementation from the main repo.  I will finish it off in my fork.

**Comment by maximecb** [comment]
Will give you more time. Glad to see you're working on this again :)

**Comment by maximecb** [comment]
@meadori How's things?

**Comment by meadori** [comment]
Hi @maximecb, I am still interested in it, but things are still sort of crazy at work.  So, not much OSS time.  I do have some local patches for function call and definition support that I plan to clean up and push this week.

**Comment by larsbrinkhoff** [comment]
Obviously, it should run ZetaLisp.

**Comment by maximecb** [comment]
@larsbrinkhoff It's really too bad that name is taken ;)

**Comment by larsbrinkhoff** [comment]
I know, but I don't think it's a bad thing. :-)

**Comment by maximecb** [comment]
@larsbrinkhoff If we do implement a LISP though, I would want something a bit simpler and more modern than the programming language equivalent of ancient greek.

**Comment by meadori** [comment]
@maximecb , many apologies for never picking this back up.  The day job just hasn't let up in a while.

**Comment by maximecb** [comment]
It's alright, we're all busy. I think Zeta is maybe not quite mature enough to support new languages yet anyway. It will be easier once we have a package server and people can just upload language packages.
