### ISSUE TITLE
Implementation of a fast interpreter

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#3]
The current interpreter, which directly executes the object-based Zeta IR (ZIR), is unfortunately dog slow, in large part because traversing a graph of dynamic objects can't really be made fast. I would like to start writing a new interpreter which lazily compiles the ZIR into a compact, linear, flat internal IR with variable instruction length.

This interpreter will be based on the Basic Block Versioning (BBV) compilation technique I developed, and will (eventually, not at first) do some type-specialization. Other optimizations to be added may include merging very common op sequences into macro-ops to reduce dispatch overhead, and threaded interpretation. Simply put, the interpreter will do some amount of JITting, but instead of JITting to machine code, it will JIT into its own more optimized internal IR, which we have a fast interpreter for. This could also be used to simplify the writing of an actual JIT to machine code down the line. A simple and lightweight JIT could conceivably JIT-compile the internal IR to machine code. The interpreter itself will remain maintainable and highly-portable.

Summary of desirable features:
- Lazy compilation of object-based ZIR into internal flat bytecode IR (IIR)
- IIR will have variable length instructions for compactness
- IIR will be more optimized, have less branches
- Lazy (re)allocation of stack frame slots for compact stack frames (after MVP)
- Threaded interpretation of IIR (after MVP)
- Fusion of very common ZIR op sequences into IIR macro-ops to reduce dispatch overhead (after MVP)
- Elimination of dynamic type checks (later, after MVP)
- Incremental inlining (for later, not at first)

The first prototype will be kept intentionally basic and simple (MVP), and will make some shortcuts, such as allocating fixed-size sack frames only. The first prototype will not be a threaded interpreter, and will not do type-specialization.

Milestone: I'm presenting at PolyConf in July 2017. I would like to have the new interpreter working before then, because the current performance level is going to turn a lot of people off. Right now, Zeta VM runs about 200K instructions per second. I would like to reach 100MIPS, maybe more. This will make it possible to use Zeta to run a wide variety of applications, including simple games.

Plan of action: I will begin laying down some code for the MVP shortly. The MVP will use BBV, but will do no type-specialization, no op fusion, and will use a switch case for dispatch. It will also use a fixed-size stack frame for simplicity. I anticipate that the MVP will still perform an order of magnitude or two better than the current interpreter.

**Comment by maximecb** [comment]
The initial version of the fast interpreter is in place. It's about 7x faster than the old one, and reaches 200 MIPS on simple loop code. I intend to make many improvements to it. It does no type specialization at the moment. For now, however, I will focus on adding features like exceptions, which are very useful for testing and debugging.

**Comment by Maaarcocr** [comment]
I'm not sure if you need any help here, but if you do I would be more than happy to contribute! :) 

I was planning to try out a simple implementation of a stop-the-world GC for zeta, but I would also love to learn more about this! :) 

I'm happy to work on both, so let me know!

**Comment by maximecb** [comment]
@Maaarcocr I might need help with it.

The challenge would be that it's kind of an unusual interpreter. It does some amount of compilation and optimization work. It's going to be based on the basic block versioning technique I developed during my PhD.

There are links to papers on the topic and videos of presentations I've given on this page:
https://pointersgonewild.com/about/

Another thing you could potentially help me with is that we're going to need to write an in-memory x86-64 assembler to eventually build a JIT compiler. I've written one in D before. It might sound daunting, but it's actually not that bad.

**Comment by Maaarcocr** [comment]
I've read the paper and I kinda understood the main point of lazy bbv. 
What I've understood is: you only JIT a specialised version of the code on need, reducing the amount of type checking needed in the code. So, the next time the code call a specific function if arguments with different types are passed, then new machine code will be generated that adapts to the new types.

I may reread the paper and maybe read Higgs source code :) 

I would be happy to work on the assembler or really anything else!

**Comment by maximecb** [comment]
I played with the audio API a little bit yesterday. It seems that right now, the interpreter is still too slow to generate audio in real-time. That is, it takes more than one second to generate a second of very basic audio (ie: a sine wave).

The next two things I can see being done for performance are:

1. Optimizing function calls with inline caches. This will probably provide a big boost.

2. Optimizing jumps to jumps and the likes. Right now, there are many basic blocks in generated Plush code that contain just a jump instruction. It should be possible to avoid generating a jump to a jump. This should provide a reduction in the final instruction count and a slight performance improvement.

**Comment by maximecb** [comment]
I've implemented the jump optimization. The generated code size is now smaller, but there is no measurable speedup. This leads me to think that function calls, and the lack of string interning in Higgs, are likely much bigger performance issues.

**Comment by krypt-n** [comment]
Indeed, string stuff seems to be the current bottleneck. 45% of the time is spent converting `String`s to `std::string`s for comparison in `getSlotIdx`. A straighforward fix (use strncmp instead of converting to `std::strings`) brings some speedup:
```
Before:
benchmarks/img_fill.pls              2853 ms
benchmarks/incr_field_1m.pls         4785 ms
benchmarks/fcalls_10m.zim            9897 ms
benchmarks/fib29.pls                 7202 ms
benchmarks/loop_cnt_100m.zim         5089 ms
benchmarks/plush_parser.zim          2104 ms
benchmarks/saw_wave.pls              6942 ms
benchmarks/sine_wave.pls             8295 ms
--------------------------------------------
geometric mean                       5276 ms

After:
benchmarks/img_fill.pls              1107 ms
benchmarks/incr_field_1m.pls         2931 ms
benchmarks/fcalls_10m.zim            5925 ms
benchmarks/fib29.pls                 3985 ms
benchmarks/loop_cnt_100m.zim         5092 ms
benchmarks/plush_parser.zim           710 ms
benchmarks/saw_wave.pls              3220 ms
benchmarks/sine_wave.pls             3783 ms
--------------------------------------------
geometric mean                       2761 ms
```

Would you want a PR for that or do you want to implement string interning right away?

**Comment by krypt-n** [comment]
Another low-hanging fruit is to move the `getSrcPos` call into the if in `checkArgCount`:
```
benchmarks/img_fill.pls               481 ms
benchmarks/incr_field_1m.pls         1430 ms
benchmarks/fcalls_10m.zim            2422 ms
benchmarks/fib29.pls                 1987 ms
benchmarks/loop_cnt_100m.zim         5094 ms
benchmarks/plush_parser.zim           337 ms
benchmarks/saw_wave.pls              1347 ms
benchmarks/sine_wave.pls             1656 ms
--------------------------------------------
geometric mean                       1374 ms
```

**Comment by maximecb** [comment]
Nice profiling work. Yes I think it would make sense to apply those fixes right away. It would motivate the troops if Zeta gains a nice 3x speed boost. 

String interning won't be too difficult to implement because I already gave some [D code that does this for Higgs](https://github.com/higgsjs/Higgs/blob/master/source/runtime/string.d). It should be fairly straightforward to port. The Zeta version will use murmurhash like Higgs. Could use a C++ unordered_map of Value objects to store the strings. The Value objects will act as GC roots eventually (when there is a GC).

Sidenote: we must address this... problem:

```
time ./zeta benchmarks/fib36.zim 
14930352

real	1m26.803s
user	1m22.276s
sys	0m3.717s

time python benchmarks/fib36.py 
14930352

real	0m6.370s
user	0m6.025s
sys	0m0.156s
```

Eventually, I would like Zeta to properly kick cpython in the gonads. Possibly, with inline caching, we will reach that goal.

**Comment by maximecb** [comment]
I just implemented inline caching on function calls. It delivers a decent speedup.

Before:
```
benchmarks/img_fill.pls              2563 ms
benchmarks/incr_field_1m.pls         1929 ms
benchmarks/fcalls_10m.zim            2567 ms
benchmarks/fib29.pls                 3979 ms
benchmarks/loop_cnt_100m.zim         3903 ms
benchmarks/plush_parser.zim          2398 ms
benchmarks/saw_wave.pls              4569 ms
benchmarks/sine_wave.pls             5900 ms
--------------------------------------------
geometric mean                       3259 ms
```

After, with inline caching:
```
benchmarks/img_fill.pls              2463 ms
benchmarks/incr_field_1m.pls         1228 ms
benchmarks/fcalls_10m.zim             802 ms
benchmarks/fib29.pls                 1801 ms
benchmarks/loop_cnt_100m.zim         4025 ms
benchmarks/plush_parser.zim          2294 ms
benchmarks/saw_wave.pls              3963 ms
benchmarks/sine_wave.pls             4992 ms
--------------------------------------------
geometric mean                       2305 ms
```

Interestingly, the fcalls and fib29 are about twice as fast. However, plush_parser barely changes, and other benchmarks get much less of a speedup. It's quite likely that object property lookups are most of the overhead there.

I will try to add inline caching to object property lookups as well.

@krypt-n Can you make a PR for your strncmp fix? :)

**Comment by krypt-n** [comment]
First, sorry for the delay

Combining the performance improvements seems to have quite the impact:

```
benchmarks/img_fill.pls               327 ms
benchmarks/incr_field_1m.pls          670 ms
benchmarks/fcalls_10m.zim             962 ms
benchmarks/fib29.pls                  763 ms
benchmarks/loop_cnt_100m.zim         5092 ms
benchmarks/plush_parser.zim           234 ms
benchmarks/saw_wave.pls               749 ms
benchmarks/sine_wave.pls              920 ms
--------------------------------------------
geometric mean                        777 ms
```

And trying to reproduce the comparison with python on my machine:
```
~/src/zetavm time ./zeta benchmarks/fib36.zim
14930352
./zeta benchmarks/fib36.zim  5.20s user 0.00s system 99% cpu 5.201 total

~/src/zetavm time python benchmarks/fib36.py 
14930352
python benchmarks/fib36.py  7.14s user 0.00s system 99% cpu 7.146 total
```
(python2 is a bit faster than python3, but still slower than zeta)

**Comment by Maaarcocr** [comment]
I could try to implement String Interning if no one is already working on it.

**Comment by maximecb** [comment]
@Maaarcocr Sure :)

**Comment by maximecb** [comment]
@krypt-n We unfortunately aren't quite beating cpython yet. The fib36.zim benchmark isn't really a fair comparison, because it does no type checking, has no dynamic property lookups, etc. It's hand-written bytecode.

This is a bit more fair:

```
time ./zeta benchmarks/fib36.pls 
14930352

real	0m18.963s
user	0m18.745s
sys	0m0.091s
```

I will try to implement inline caching on object property lookups later today, and maybe that will help. Either way, we're quite close, despite the fact that our fib code has runtime function calls for every primitive operator!

**Comment by krypt-n** [comment]
Do you still have the chained-jump patch around? I am interested in how you implemented it and if it has has more benefits, now that the rest of the interpreter is faster.

**Comment by maximecb** [comment]
It's already applied, should be able to find it in the commit log. It's not
very complex. It just avoids writing a jump when falling through to the
branch target directly.

**Comment by krypt-n** [comment]
So, how do you want to proceed here?
* Threaded Interpretation kind of contradicts compact IR, since all opcodes need to be full pointers
* Is the fusion of common op sequences meant to be dynamic or static?
* Another approach could be to improve the code generators of plush and/or the other languages

**Comment by maximecb** [comment]
> Threaded Interpretation kind of contradicts compact IR, since all opcodes need to be full pointers

Yes and no. The pointers would replace the opcodes in the flat IR. It would be less compact, but still much more compact than the object-based IR. I think the obvious thing to do here would be to benchmark both. Full pointers will mean bigger bytecode, which is worse for the instruction cache, but I think it might still win, that's what the conventional wisdom says anyway, that direct threaded is quite a bit faster.

Another thing that might be worth looking at is that the current flat IR ignores memory alignment. I believe modern i7 CPUs are much better with unaligned memory accesses, but it could still be impacting performance.

> Is the fusion of common op sequences meant to be dynamic or static?

I was thinking static. We could have a fused `get_field` with a static field name, for example. We would design fused internal opcodes for very common sequences. The outwardly-facing object-based IR would not change.

> Another approach could be to improve the code generators of plush and/or the other languages

Yes, that's definitely possible, and it might make sense in some cases. I want to have strong optimizations built into the VM itself though, and the reason for that is that I want every language to run fast, as much as possible. If we rely on people optimizing their own bytecode, then a large fragment of people won't do it. The other thing is that the VM is going to be using basic block versioning, and it will be able to do things that go beyond what you can do when working at the level of control flow graphs.

One thing I want to do at the interpreter level in the next few months is what I call "incremental inlining". This will allow the interpreter to inline function calls, one basic block at a time. At the moment, function calls are quite expensive in Zeta, so this should produce a big speedup. It would also allow exposing new optimization opportunities. At the moment, every add/subtract/multiply/etc is done through a runtime function call. If we can eliminate all the calls from "hot" pieces of code, we're going to see a huge boost. I think this will easily allow us to jump way past the performance of CPython. We might actually end up with one of the fastest interpreters around.

**Comment by krypt-n** [comment]
I'm gonna give it a shot

**Comment by maximecb** [comment]
Curious to see what results you get! :)

**Comment by krypt-n** [comment]
current master:
```
benchmarks/loop_cnt_100m.zim         2851 ms
benchmarks/incr_field_1m.pls          502 ms
benchmarks/get_field_1m.pls           485 ms
benchmarks/set_field_1m.pls           297 ms
benchmarks/fcalls_10m.zim             680 ms
benchmarks/fib29.pls                  559 ms
benchmarks/fib36.zim                 3117 ms
benchmarks/plush_parser.zim           128 ms
benchmarks/img_fill.pls               181 ms
benchmarks/saw_wave.pls               455 ms
benchmarks/sine_wave.pls              543 ms
benchmarks/func_audio.pls            1943 ms
benchmarks/rand_floats_1m.pls        3380 ms
benchmarks/zsdf.pls                  7862 ms
--------------------------------------------
geometric mean                        829 ms
```


Hmm..well
* I implemented threaded interpretation based on gcc computed gotos: https://github.com/krypt-n/zetavm/tree/threaded

```
benchmarks/loop_cnt_100m.zim         3055 ms
benchmarks/incr_field_1m.pls          514 ms
benchmarks/get_field_1m.pls           501 ms
benchmarks/set_field_1m.pls           303 ms
benchmarks/fcalls_10m.zim             778 ms
benchmarks/fib29.pls                  548 ms
benchmarks/fib36.zim                 3176 ms
benchmarks/plush_parser.zim           131 ms
benchmarks/img_fill.pls               184 ms
benchmarks/saw_wave.pls               475 ms
benchmarks/sine_wave.pls              552 ms
benchmarks/func_audio.pls            1959 ms
benchmarks/rand_floats_1m.pls        3323 ms
benchmarks/zsdf.pls                  7909 ms
--------------------------------------------
geometric mean                        851 ms
```

...and it is not faster. Additionally the current version is probably incorrect since keeping a writable `op` reference around makes it even slower, so I replaced it. I don't know why it's slower, the generated assembly looks okay, but I'm not an expert on that.

* I implemented simple instruction combination: https://github.com/krypt-n/zetavm/tree/lookahead

```
benchmarks/loop_cnt_100m.zim         2485 ms
benchmarks/incr_field_1m.pls          442 ms
benchmarks/get_field_1m.pls           427 ms
benchmarks/set_field_1m.pls           260 ms
benchmarks/fcalls_10m.zim             658 ms
benchmarks/fib29.pls                  465 ms
benchmarks/fib36.zim                 3046 ms
benchmarks/plush_parser.zim           122 ms
benchmarks/img_fill.pls               161 ms
benchmarks/saw_wave.pls               388 ms
benchmarks/sine_wave.pls              475 ms
benchmarks/func_audio.pls            1643 ms
benchmarks/rand_floats_1m.pls        2856 ms
benchmarks/zsdf.pls                  6846 ms
--------------------------------------------
geometric mean                        735 ms
```
...which actually improves things a little bit. It currently combines 
`push 1, add -> inc`, `push 1, sub -> dec` (this causes the speedup in the loop_cnt_100m case) and
`get_local, has_tag, if_true -> if_has_local_tag` (speeds up plush arithmetic).

The questions is what to do next. Is there a obvious mistake in the threading implementation that causes the slowdown? And how could we identify worthwhile instructions to combine?

**Comment by maximecb** [comment]
> Is there a obvious mistake in the threading implementation that causes the slowdown? 

I'm not sure. It might have to do with alignment. Possibly, in order to get the best performance possible, we might have to make sure that every value stored in the code heap is aligned. The fact that even loop_cnt_100m slows down tells us that this is probably not a matter of code getting too big and not fitting in the cache.

> And how could we identify worthwhile instructions to combine?

Nice. Sizeable difference on the loop_cnt_100m benchmark from combining opcodes. More than 10% speedup.

Some comments and nitpicks:

1. Other ops to combine, you could look into having a get_field that uses a constant name string. Right now, we push field names, then do get_field on every access. Same for set_field.

2. I wouldn't add any more cases beyond set_field, get_field and really obvious stuff. I'm sure there are a lot of possible combinations we can think of, but the more we add, the more complex the interpreter becomes, and this will just get in our way when we add more sophisticated optimizations later, it will be that much more code to maintain.

3. I think that if we really want to understand what's going on in the internal IR and make informed decisions, we're basically going to need a disassembler. Otherwise we can only kind of imagine what is happening, but that is going to get increasingly difficult, since the interpreter actually generates and modifies code as it runs.

4. I wouldn't use a map to look up opcode combinations though. I would hardcode it in the `compile` function. You can make helper functions, but it would be cleaner and more efficient IMO if you could go `if op == "foo" && nextOp == "bar"` instead of doing a search in a map, which really just adds indirection and obscures what is going on IMO.

5. `if_has_local_tag`, you should name `if_local_has_tag` ... But I actually have plans to mess with the way if statements are handled, so I think we shouldn't fuse anything with ifs for the moment.

**Comment by krypt-n** [comment]
> I think that if we really want to understand what's going on in the internal IR and make informed decisions, we're basically going to need a disassembler. Otherwise we can only kind of imagine what is happening, but that is going to get increasingly difficult, since the interpreter actually generates and modifies code as it runs.

I did look at execution traces to choose the three combinations I implemented, but more structure, especially regarding branching and controll flow would indeed be useful.

> I wouldn't use a map to look up opcode combinations though. I would hardcode it in the compile function. You can make helper functions, but it would be cleaner and more efficient IMO if you could go if op == "foo" && nextOp == "bar" instead of doing a search in a map, which really just adds indirection and obscures what is going on IMO.

I agree that a map is overkill for the few cases that are actually gonna be usefull and I'll replace it, but I think that the combination of instructions needs to stay seperated from the "compiling". A single `(Object, Object) -> Value` helper function replacing the map seems like the probable compromise.

**Comment by maximecb** [comment]
Closing this for now. Will open more specific issues when we get to inlining, etc.
