### ISSUE TITLE
Trying to implement a language - Marco

### ISSUE THREAD

**Issue by Maaarcocr** [zetavm/zetavm#36]
I'm opening this issue to have a place where I can ask questions that could also be relevant to people in future trying to do similar things to me while implementing a language with zetaVM.
For other less relevant issues I may contact @maximecb in private (I sent you a request on Hangouts) in order to reduce the spam of silly questions here. 

Yesterday I was trying to come up with some ideas about the language I want to implement. While doing so, I stumbled upon one problem that I can't solve in my head.

The problem: I want the ability to get all the fields in an object, so that I can iterate over them or create a new deep copy of the object. I know that this is possible inside the VM, but as far as I know there is no instruction that gives me this ability. Would it be possible to implement this with the instructions that already exist or should we add a new instruction to zeta for this?

**Comment by maximecb** [comment]
I think we may want to add a "get_field_list" instruction which returns an array of field name strings. It's going to be needed by other language implementations as well.

**Comment by werediver** [comment]
@maximecb Are you planning to implement features like inheritance (either class-based or prototypal) and virtual method calls (if applicable) in the VM or delegate them to language implementers?

**Comment by maximecb** [comment]
The VM has native support for dynamic typing, so you already have virtual method calls in the form of duck typing. Function calls involve a dynamic lookup.

As for prototypal inheritance, that is delegated to language implementers. It seemed better that way to me because it allows the VM's object model to remain simpler. It's not difficult to implement this in your own language. Plush exemplifies it: https://github.com/zetavm/zetavm/blob/master/plush/runtime.pls#L432

**Comment by maximecb** [comment]
Following the discussions we've had, I added the hidden function/closure argument in: 4931dffa9d304116d2f3c9a3ec78dfa5b323b42b

Now, every function receives the function object being called as the last argument. Every function must have `num_locals >= num_params + 1`.

Closures can be implemented by performing [closure conversion](http://matt.might.net/articles/compiling-scheme-to-c/). That is, you have to do some analysis work to determine, when you have nested functions, which variables are captured from parent functions. The parent functions can then create closures by creating objects (cells) to wrap the locals that will be captured, and storing reference to these objects on closure objects. Each closure being created will result in the creation of a new function/closure object to capture local variables.

The closures, when called, receive a pointer to the function/closure being called, in the hidden closure argument. This is simply the local variable at index `num_params`. From this, the closures can read fields on the function object and access closure variables through the closure cell objects.

Let me know if you have any questions, I'll be happy to provide more help.

**Comment by maximecb** [comment]
Added this document, which may be helpful to newcomers wanting to implement a language: https://github.com/zetavm/zetavm/blob/master/docs/exec_model.md
