### ISSUE TITLE
Implementation of a JavaScript front-end

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#4]
It would be great to have support for JavaScript, or a subset of it. This would allow us to use existing JS code. The Plush language is quite similar to JS, so the [Plush parser](https://github.com/maximecb/zetavm/blob/master/plush/parser.pls) could be used as a base to begin implementing JS support.

**Comment by dirk** [comment]
As parsing JS is a huge headache, what about using a FOSS parser (eg. Facebook's [`libfbjs`](https://github.com/facebookarchive/libfbjs)) and then only having to tackle traversing/transforming the parser's produced AST into an image?

**Comment by maximecb** [comment]
I would rather minimize dependencies on external libraries. I wrote a parser from ES5 in D for my Higgs project and I think it's probably not as hairy as you think:
https://github.com/higgsjs/Higgs/blob/master/source/parser/parser.d

IIRC Brendan Eich also wrote a JS parser in JS which could presumably be ported without too much difficulty.

Another thing to keep in mind is that it could be OK to start with a subset of ES5 and add support for features gradually. I think it's OK not to support all of JS syntax from the start.

**Comment by dirk** [comment]
> Another thing to keep in mind is that it could be OK to start with a subset of ES5 and add support for features gradually. I think it's OK not to support all of JS syntax from the start.

Cool! Having spent a bit of time in grammars for ES6, JS parsing seemed... daunting. :joy:

**Comment by maximecb** [comment]
@dirk Are you still working on this?

**Comment by dirk** [comment]
@maximecb: Sure! Could use a distraction from work.

**Comment by maximecb** [comment]
Apologies, but I'm unfortunately going to close this issue for now and remove the associated code. I will be presenting Zeta at a conference next weekend, and I would prefer that people see working language implementations when looking at the repository.
