### ISSUE TITLE
How lines in image files can be mapped to lines in source files?

### ISSUE THREAD

**Issue by motet-a** [zetavm/zetavm#43]
If an error occurs somewhere in a running program, is it possible to get the corresponding line number in the source file? Are related debugging features implemented in Zeta?

JavaScript transpilers and browsers use a similar system called source maps, and GCC/GDB also use a similar system with the `-g` option.

Thanks.

**Comment by maximecb** [comment]
Call, throw and abort instructions can be annotated with an `src_pos` field. This should point to an object with `src_name`, `line_no` and `col_no` fields, so when you generate an image, you can store source position information. The image files themselves, while they are human-readable, aren't really meant to be written by hand, that is you wouldn't really develop software that way, but you can still add `src_pos` objects in there manually if you want to.
