### ISSUE TITLE
Overflow in arithmetic causes Zeta to crash

### ISSUE THREAD

**Issue by tommyettinger** [zetavm/zetavm#56]
You can test this easily by adding the test line:

```
assert (65537 * 65535 == -1);
```

To any test you want, like simple_exprs.pls.  For me on Windows 7, this gives a rather useless standard-Windows-OS error with this set of details:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	zeta.exe
  Application Version:	0.0.0.0
  Application Timestamp:	594b67d5
  Fault Module Name:	zeta.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	594b67d5
  Exception Code:	40000015
  Exception Offset:	0000000000030888
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	e270
  Additional Information 2:	e27047525f7bbc7539be3fd841a27205
  Additional Information 3:	5310
  Additional Information 4:	531031f3f1e05e5a47a30dcb69debe58
```

I'm not sure precisely why this is, but I suspect the Word union didn't get fully updated to use 32-bit math while it allows 64 bits internally, and perhaps overflowing is setting bits beyond the initial 32.

EDIT: Overflow may not be the correct term, since the example given should still fit within 32 bits and it still crashes. It seems related to wrapping around from positive to negative. This is not tied to multiplication in particular; the code

```
assert (2147483647 + 2147483647 <= 0);
```

Will also produce the same type of crash, and it also fits in 32 bits (but should wrap to be a negative number).

This is currently stopping any progress on the RNG code, where almost everything involves overflow. I'll help however I can on this, but I don't know any of the C/C++ intricacies in play here (I just learned that there are more than 2 kinds of cast in C++ today...).

**Comment by krypt-n** [comment]
This is currently expected behaviour, since zeta is compiled with `-ftrapv`. With this flag, gcc emits code that aborts the program if an overflow or underflow occurs.

**Comment by maximecb** [comment]
Ok done. It works now :)

**Comment by tommyettinger** [comment]
Nice work on the fast fix! This definitely fixes any issues I was having, so the random number generator PR is incoming.

**Comment by krypt-n** [comment]
Note that this change speeds up the benchmarks a little bit, since there are no frequent calls to overflow-checking operations anymore.

**Comment by maximecb** [comment]
That's funny. I know we can get a bit of a speedup by disabling asserts too. Right now that's unsound because some of the asserts are performing necessary runtime checks, but I will eventually replace all type  and bound checks by explicit checking instructions in the VM, so that we can optimize them away.
