### ISSUE TITLE
Global & local package names, feedback wanted

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#58]
Soliciting opinions & feedback regarding this issue. This is an problem that we have to address before the zeta package manager goes online, and preferably should be solved early on.

Currently, when you import a package in Zeta, there's a non-trivial amount of logic going on in `packages.cpp`: https://github.com/zetavm/zetavm/blob/master/vm/packages.cpp#L496
https://github.com/zetavm/zetavm/blob/master/vm/packages.cpp#L556

I have two regexes to validate the package path format in there. I'm wanting to force packages paths to be of the form "foo/bar/bif/N", where N is a version number. One of the issues there is that people may want to import local files as packages. This is in conflict with my desire to standardize the paths of packages in the packages directory, the "standard" packages that come with the VM or will be managed by the package manager.

I'm starting to think that probably, what we need is a different package name syntax for global/non-local packages. Those being the core packages, what's under `packages`, those that will be managed by the VM and package manager.

I was thinking that we could force global package names to begin with a colon character, like this:

```
var io = import ":core/io/0";
```

This would be in contrast to local package names, which can be any local file path:

```
var myPkg = import "/user/foobar/../some_unix_path.pls";
```

Having a separate format for non-local path will simplify the path validation logic, and it might have some security benefits. That is, it's more difficult to accidentally import a local package when you wanted to import a global one, and vice versa.

It is technically possible on unix/linux to create a path or file name with a colon in it, but with this syntax, any package with a name starting with ":" will be looked up as a global package. To look up a local module with a colon, you would do:

```
var myModuleWithAWeirdName = import "./:colonFileName.pls";

**Comment by Maaarcocr** [comment]
Another option would be to use something like:
```
var io = import "<core/io/0>"
```
for global packages. I'm not really sure if this is any better than the : syntax.

Another option is that all local packages must have a path like: './my_module/my_file'

**Comment by maximecb** [comment]
I guess the C preprocessor did solve that very same problem. Copying C's include syntax would have the advantage that it's something people are kind of familiar with. However, it seems redundant to have both quotes and angle brackets. I want people to be able to use global package names to launch programs from the Zeta command line (eg: for the REPL, but also if you want to publish programs through the package manager), so I think I'll go with the colon syntax. It might work better for that.

**Comment by maximecb** [comment]
@Maaarcocr I actually tried the colon name approach, and after some further thought, I think your suggestion makes more sense.

Having the angle bracket syntax for import makes it more secure, because it means we can truly have a "global import" and a "local import" mode. The local import mode can read files on the file system, and should probably be disabled by default, eg: disabled unless you say run zeta with `--allow_local_imports`. 

The similarity with C++ might also help people understand what's happening, and the difference between import <foo> and import "foo".

**Comment by Maaarcocr** [comment]
With local import turned off by default, would that mean that it would need to be implemented by implementers in their langauge? For example, they would need to do something similar to what you do for runtime.pls in cplush, wouldn't they?

**Comment by maximecb** [comment]
I've changed my mind. Local imports won't be turned off by default. I've actually been giving this issue a lot of thought in the last few days, because it's tricky to get right, and the package system is a crucial feature.

Most importantly, I think that local imports need to be relative to the file being imported (as in Python). Currently, they are relative to the current working directory. However, it seems like it would make sense to be able to upload packages that are made of multiple files. For instance, maybe you don't want to implement your language all in one big file. For this to work, relative local imports need to be possible.

The tricky bit here, however, is that relative import means the `import` instruction needs to know which directory to look in when doing a relative import. We can't "bake" that information in when compiling something in cplush, because files can be moved around after they are compiled. Only ZetaVM knows where your file is when it gets loaded. To make this work correctly, I think that we will need to pass a `rel_import_path` argument to the `init()` function exported by packages.

For people implementing their own language, they can begin by supporting global imports only if that is simpler. To implement local imports, they will need to either store the `rel_import_path` value in an object when the `init(rel_import_path)` function is called, or to do all their local imports during the `init` function execution.

**Comment by maximecb** [comment]
Made it so that local package imports have to start with ./, as this seems like the simplest solution.
