### ISSUE TITLE
Core VM identifier limitations

### ISSUE THREAD

**Issue by meadori** [zetavm/zetavm#62]
While working on the Scheme implementation I discovered that the core VM has a somewhat limited set of legal identifiers (sequences of alphanumeric characters and underscores).  Scheme, OTOH, is quite permissive (interestingly, scanning is more complicated than parsing).  For example, many common functions end with '?' like 'boolean?'.

In order to support multiple language properly, Zeta will to take the union of legal identifiers across all supported languages.

**Comment by maximecb** [comment]
The reason it's limited in this way is that I wanted to keep things simple in the image format (ZIM files). Object field names have a number of limits on them.

However, in your language implementation, you can name your local variables whichever way you like. If you want to have a richer set of field names than what ZetaVM currently permits, one way to do so would be to basically escape your field names. For instance, you could map ? to x3F internally. This would be invisible to the user.

If you think that this is too inelegant and annoying, it could be possible to allow arbitrary strings as object field names. It would add a bit of complexity to the ZIM image parsing, but it is doable.

**Comment by meadori** [comment]
I am not sure I follow the work around.  Eventually the identifier name has to be lowered to Zeta IR.  I can't just map "boolean?" to "booleanx3F" because someone could actually name something "booleanx3F".  That might be very unlikely, but if it did happen (Murphy's Law) it would be quite surprising.

ISTM that if the Zeta identifier set stays as is, then language implementers will have to implement name mangling algorithms to ensure that identifier names can (1) be lowered to Zeta and (2) won't conflict.  I could see this be a problem for a lot of languages.  Javascript, for example, allows $ in identifiers, which wouldn't be allowed in a valid Zeta identifier.

I haven't thought about the complexities of allowing for arbitrary strings as identifiers, but at first glance that seems like a reasonable path.

**Comment by Maaarcocr** [comment]
I think that "booleanx3F" refers to the fact that you could use the escape sequence 0x3F (which is the same as using the char ?) when translating to Zeta IR. 
If someone writes "boolean\0x3F", depending on how your language implements escaped characters, it could be equal to "boolean?", because they are actually the same string (if you think of strings as an array of characters and characters as just integers).

**Comment by maximecb** [comment]
> I can't just map "boolean?" to "booleanx3F" because someone could actually name something "booleanx3F". That might be very unlikely, but if it did happen (Murphy's Law) it would be quite surprising.

You'd have to escape the x character as well. Think C-style character escaping, with \n, \t, \\.

I think when I made this design choice, I intended to put some pressure on languages running on ZetaVM to use the same limited set of identifier characters. It's a forcing factor to try and make languages remain more compatible.

That being said, I agree that it would probably mostly get in people's way. People are likely to want more freedom, and will find it annoying to have to resort to escaping them everywhere... So it could make sense to allow arbitrary strings as object field names, in the name of making the VM more friendly to language implementers.

**Comment by Maaarcocr** [comment]
> So it could make sense to allow arbitrary strings as object field names, in the name of making the VM more friendly to language implementers.

For the sake of coherence, shouldn't also set_local accept the same kind of input? (Maybe it already does, I'm not sure)

**Comment by meadori** [comment]
> You'd have to escape the x character as well.

I must be missing something.  I understand that 0x3F is the ASCII equivalent of '?', but I don't see how you can actually escape an identifier in the IR.  Consider the following:

```
   boolean? = {
     name: 'boolean?',
     params: ['v'],
     num_locals: 2,
     entry: {}
   };
```

I currently can't write that because `isValidIdent` chokes on it.  How can I escape it?

```
   boolean\x3F = {
     name: 'boolean?',
     params: ['v'],
     num_locals: 2,
     entry: {}
   };
```

That won't work either because the identifier parsing code doesn't allow for escapes.  Even if it did, then it still wouldn't work because `isValidIdent` would still choke.  AFAICT, escaping is only allowed in string literals, which you can't use for field names.

**Comment by maximecb** [comment]
> shouldn't also set_local accept the same kind of input? (Maybe it already does, I'm not sure)

@Maaarcocr set_local takes an index number. A stack frame slot index. The VM itself has no notion of local variable names, except for function parameters.

> boolean\x3F = {

@meadori Aaah, no. What I meant is that I might allow escaping of field names, eg:

myObject = {
  "thefield?": 3
};

This can be useful if you have a "global object" in which you store your global variables, as Plush is doing.

However, the names of identifiers in the ZIM file should actually not be relevant. The purpose of ZIM files is to serialize a graph of objects. The identifier names in the ZIM files are just convenience names which you can use to refer to other objects, but they are immutable, they are not variables, and should not be visible inside your language implementation.

What you probably want to do is:

```
    someFunction_1355 = {
     name: 'boolean?',
     params: ['v'],
     num_locals: 2,
     entry: {}
   };

    globalObject = {
        // strings for field names not supported yet, but I will probably add it soon
        "boolean?": @someFunction_1355
    };
```

That is, the global object would have a field with the name `boolean?` which maps to your function. The identifier which is used to refer to the function inside the ZIM file is never seen by the implementation.

**Comment by Maaarcocr** [comment]
> @Maaarcocr set_local takes an index number. A stack frame slot index.

My bad, I don't know what I was thinking.

**Comment by maximecb** [comment]
Thanks for voicing your concern. I will add the string field names to my TODO list. It might take a bit though as I will be at PolyConf in Paris for the weekend, and need to work on my presentation some more. Then there's a refactoring of the package lookup system that I want to do. It will get done though :)

Can you keep progressing in other areas in the meantime?

**Comment by meadori** [comment]
> Can you keep progressing in other areas in the meantime?

I can!  I implemented a simple name mangling scheme in the meantime.  See #63.

**Comment by maximecb** [comment]
I implemented arbitrary strings as property names in commit 3a43d53940bc4c5e3b2562eb5f0e2fd45767129c today :)
