### ISSUE TITLE
String library (std/string)

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#73]
The core VM doesn't provide very much in the way of string functionality. Just support for immutable UTF-8 strings with string interning. It seems it might be beneficial to write a standard library that has a collection of useful string functions. This is particularly relevant since ZetaVM is a tool for language implementation, and we necessarily do a fair bit of string manipulation as part of parsing.

This library should be written in Plush, and the package should go under `std/string/0`. 

See the way the math package is compiled for reference: https://github.com/zetavm/zetavm/blob/9b944eda3926a3486931106bdc24e1e74ed746ac/makefile.in#L73

Things we should probably include
- `toString`: function to convert values to a string
- `indexOf`: finds the first index of some substring
- `substr`: get a substring
- `split`: as in Python, split string based on some delimiter, produces an array
- `toLower`, `toUpper`: convert to upper or lowercase
- `strip`: remove whitespace, can also be subdivided into lstrip and rstrip
- `replace`: replace all occurrences of some substring

These don't have to be the only functions we include, suggestions welcome. Also, if you're interested in working this library, note that you don't have to implement all the functions at once, an implementation of just a subset of these would already be valuable.

**Comment by krypt-n** [comment]
Ah, I was just writing an issue about something like this.

* Some of these functions also apply to arrays (substr and indexOf), so an array support library could be added aswell.

* These functions would probably need to understand UTF-8 eventually

* I'd also propose a simple version of the python string formatting with {}s

**Comment by maximecb** [comment]
> Some of these functions also apply to arrays (substr and indexOf), so an array support library could be added as well.

Yes, an array library would be useful as well. The function names could be intentionally made similar between the libraries (ie: both libs can have `indexOf` and `concat` functions with the same arguments). I wouldn't necessarily recommend sharing code between the two, however, because different instructions will be used to implement string vs array functionality.

> These functions would probably need to understand UTF-8 eventually

Yes, we should try to be as UTF-8 compliant as possible, and we should add plenty of tests. I'm OK with a first version not being fully compliant, but we should aim to get there.

> I'd also propose a simple version of the python string formatting with {}s

The Plush language needs to remain simple IMO, but there will eventually be extension mechanisms.

Do you think we could implement simple formatting functions as part of the library, even though we don't have language syntax for this yet?

**Comment by maximecb** [comment]
> I'd be interested in working on this.

@krypt-n Please do! 👍  :) This is going to be a good step towards making Zeta/Plush more usable.

**Comment by krypt-n** [comment]
> The Plush language needs to remain simple IMO, but there will eventually be extension mechanisms.
>
> Do you think we could implement simple formatting functions as part of the library, even though we don't have language syntax for this yet?

I don't mean supporting (program)variable names in the format strings, just something like `'{} {}'.format(1, 2)` (instead of printf syntax). That can easily be implemented without language support.

**Comment by maximecb** [comment]
> I don't mean supporting (program)variable names in the format strings, just something like '{} {}'.format(1, 2) (instead of printf syntax). That can easily be implemented without language support.

Yes that seems workable. Zeta doesn't have variadic functions yet though. Another possibility would be to use an object as a namespace for substitutions:

```
format('{x} foobar {y}', {x: 77, y:102});
```

I think we should make it so every string library function takes a string as their first argument. Then in the Plush runtime, we can create a string prototype object that is used to do method lookups. That is, the Plush language can expose those functions as string methods, but the `std/string` library won't have a concept of methods per-se, just functions that operate on strings.

**Comment by krypt-n** [comment]
Should the testcases be included in the library package?

**Comment by maximecb** [comment]
Good question. So far I've been putting them in a separate file. You could put yours under `/tests/plush/strings.pls`.

Eventually when we have a package manager, it might make sense to have a standard way of putting tests in packages themselves, but I haven't worked out how that should be done.

**Comment by boomshroom** [comment]
This would be nice and quite useful.

One feature I'd like to see is a way to override the printing facility for custom types. In the language that I'm designing for this VM, I has string() methods on each of my AST types to assist with debugging.

Another thing that may be out of scope for this package, but would be nice to see, is grapheme cluster indexing. Rather than advancing by byte or by unicode codepoint, being able to advance by grapheme cluster could be useful for foreign languages where a single 'character' could be many separate codepoints. This would probably be better suited to a unicode package.

**Comment by maximecb** [comment]
> One feature I'd like to see is a way to override the printing facility for custom types.

@boomshroom @krypt-n We could make it like JavaScript, and check if objects have a `toString` method which we can call. That seems like the simplest solution.

> Another thing that may be out of scope for this package, but would be nice to see, is grapheme cluster indexing. Rather than advancing by byte or by unicode codepoint, being able to advance by grapheme cluster

I don't know how that works, but open to adding it to our wishlist.

**Comment by maximecb** [comment]
@krypt-n I just merged your pull request. Well done.
