### ISSUE TITLE
Improving User-Friendliness

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#74]
I think there are probably many small things we can do to make Zeta more user-friendly. You may be getting cryptic error messages, running into strange bugs, segmentation faults, or odd behaviors. 
This is the place to report these kinds of problems. Small issues like these often go unreported, and may discourage people from using Zeta. By telling us about them, you can help us fix them, add new tests, and ensure that other users don't run into the same problem.

**Comment by krypt-n** [comment]
Stacktraces on assertion failure would help debugging.

**Comment by Maaarcocr** [comment]
It would be good to have an unified way of doing documentation. 
I wouldn't add it to ZetaVM directly, but maybe creating a library in plush (or any other language) that can help adding documentation comments support for the implementers would be cool. Also, we would have an unified style for the generated documentation (I guess it would an HTML file)

**Comment by maximecb** [comment]
You mean a Plush library to do documentation comment parsing and generate HTML (or markdown) ?

**Comment by Maaarcocr** [comment]
Yes. We can surely use an existing tool, but it would be good to have just one way of doing documentation for all the languages (imo).

**Comment by maximecb** [comment]
Would have to think about what that is. I suggest opening another issue. The main problem I see is that different languages will have different sets of features. So, we can document functions and declarations, but some language may have classes and others not, etc. Zeta can support having comments attached to functions themselves, like Python doc strings, but unsure how far that gets us. There are a number of things to consider.

**Comment by krypt-n** [comment]
I'm taking a look at stacktraces right now and it seems that virtually all functions in plush are currently unnamed, which limits the usefulness a bit. How do other languages with a lot of unnamed functions handle this?

**Comment by maximecb** [comment]
@krypt-n I had to address that issue in Higgs / JavaScript as well. What we can do is have a simple pass in the Plush parser that traverses the AST and finds patterns of the form:

```
var f = function () ...
f = function () ...
o.m = function () ...
```

And assigns the variable/field name to the function's `name` field.

**Comment by maximecb** [comment]
@krypt-n Created issue #82 for stack traces.

**Comment by maximecb** [comment]
Simple things we can do for user-friendliness:

- Stack traces on exceptions (work in progress)

- Documenting the stack frame layout and execution model under `/docs`

- Creating a style guide / how to contribute guide under `/docs`

**Comment by maximecb** [comment]
I added the execution model and contributor guide documents. We have an issue for stack traces. Will close this issue for now as it's not very specific.
