### ISSUE TITLE
Array library (std/array)

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#78]
In a similar vein to https://github.com/zetavm/zetavm/issues/73, we should create a library of useful array functions. These functions should, where it makes sense, use the same naming and argument conventions as the string utility library.

This library should be written in Plush, and the package should go under `std/array/0`.

Functions we probably want to see:

- [x] `indexOf`

- [x] `contains`: checks that `indexOf(k) != -1`

- [x] `replace`

- [x] `slice`: this would be analogous to `substr` ? If so, we may want to have a `slice` function in the string library as well.

- [x] `concat`: concatenate two arrays together into a new one

- [x] `append`: append the contents of an array to another

- [x] `map`: functional-style array transformation.

- [x] `flatMap`: takes a function that produces an array of elements and concatenates the resulting elements.

- [x] `forEach`: functional-style iteration.

- [x] `arrayEq`: shallow array equality testing

- [x] `sort`: sort the array in-place, takes a comparison function

- [x] `binarySearch`

Suggestions for functions to add or on how to better organize things are welcome.

**Comment by ashwanidausodia** [comment]
@maximecb What would be the semantics of `replace` function?

**Comment by maximecb** [comment]
@ashwanidausodia Good question. I would say replace based on identity comparison (Plush `==` operator semantics).

**Comment by ashwanidausodia** [comment]
I have one question. If array is separate package you have to write
```
var array = import("std/array/0")
var index = array.indexOf(myArr, 4);
```
NOT
```
var index = myArr.indexOf(4);
```
Tell me if I am wrong.

**Comment by maximecb** [comment]
That's right, but we can "cheat"

We can make the `rt_getProp` function of the Plush runtime (plush/runtime.pls) do a lookup of array methods on an array prototype object which maps to these functions. So, in that way, of array methods are written with the array as the first argument, language runtimes can reuse them.

**Comment by maximecb** [comment]
Added `arrayEq` function

**Comment by krypt-n** [comment]
`sort`, `contains` (`indexOf != -1`) and `binary_search` would be usefull additions to this.

**Comment by krypt-n** [comment]
Oh, and in the future we might want read-only slices that are only views into the original array but can be used like arrays.

**Comment by maximecb** [comment]
@krypt-n `sort` and `contains` are definitely good suggestions. What would `flatMap` do?

**Comment by krypt-n** [comment]
While map takes a function that produces a single element and applies it to an array, flatMap takes a function that produces an array of elements and concatenates them.

Consider

```
var split = function(str) { return string.split(str, " ") };
map(["a b c", "d e f"], split) == [["a", "b", "c"], ["d", "e", "f"]]
flatMap(["a b c", "d e f"], split) == ["a", "b", "c", "d", "e", "f"]
```

**Comment by maximecb** [comment]
@krypt-n I've never really seen that used before, but I'm open to it being included, sure.

**Comment by maximecb** [comment]
@ashwanidausodia I've updated the list so we have checkboxes for what's completed and what's missing. There are 4 functions remaining. Will you have time to complete the rest of them?

**Comment by boomshroom** [comment]
Flatmap is related to monads, which take some container/monad T<V> and a function V->T<V> that operates on the inner value and bundles the output as a single T<V>. In Rust, Option also has the same monadic behavior using and_then.

Implementation wise, flatmap should be as simple as copying the map implementation and replacing push with append. That said, I think that with the dynamic typing, it should be possible to fallback to map behavior if the function doesn't output an array. Whether or not that is preferable to crashing is debatable.

**Comment by maximecb** [comment]
@boomshroom In general, I prefer more strict behavior (throw an exception). I think that having the implementation try to bend over backwards for the user leads to all kinds of corner cases, as in JavaScript's many semantic quirks.

**Comment by jammln** [comment]
What sort algorithm would you prefer to be used? Or should it depend on the size of the array?

**Comment by maximecb** [comment]
@jammln What are the different options?

**Comment by boomshroom** [comment]
Quick sort is usually a fairly good option to start with for arrays. If need be, we can always tell it to switch to a different algorithm when the length is small.

**Comment by jammln** [comment]
I agree with @boomshroom, use something like insertion sort for small arrays and quicksort for anything bigger. I think it would have to be benchmarked for tuning where the cross over point for array size to algorithm performance is.

**Comment by maximecb** [comment]
Sure. It's also a question of how much time you're willing to put into it. Any sort implementation is better than none, so I'd be happy to have a basic quicksort just to check that box. If you're interested in implementing something more sophisticated and benchmarking it, that would be amazing too. If you're interested, you could start with a first PR for a basic implementation, and then a second for the adaptive one.

We keep some benchmarks in `/benchmarks` and there is a `benchmark.py` script to run them. Zeta now also has the ability to pass command-line arguments to programs so we can use the same script to test multiple array sizes, eg: `./zeta benchmarks/sort.pls -- 2048`.

**Comment by jammln** [comment]
Sounds good to me, I'll get to work on it.

**Comment by ashwanidausodia** [comment]
I think, For now we can close this after #89  is merged.
