### ISSUE TITLE
Clarify mapping of stack arguments to locals.

### ISSUE THREAD

**Issue by boomshroom** [zetavm/zetavm#86]
At the moment, it's rather unclear, even when reading the source code, which local variable corresponds to which function argument. For example, is the closure argument the first or last argument? If my params field is ["x", "y"], which index is assigned to each?

I'd understand if this is subject to change, but the lack of documentation is a minor stopping point for people trying to write their own languages.

**Comment by maximecb** [comment]
You're right. At the very least, we should document this in comments in `vm/interp.cpp`, and/or possibly create a document under `docs`.

The way that it works right now is that functions have a number of locals on the stack. This number must include the visible function parameters, and the hidden closure argument, so it has to be always at least 1. The closure argument maps to slot index 0. The visible parameters map to indices 1 to N. Slots above that are for local variables. These are all accessed with the `set_local` and `get_local` instructions.

Above that, there are slots for the return address and temporaries. These are not (or should not be) directly accessible through `get_local`. The values in the temp stack are conceptually in a different memory space from the local variables. They are stored on the same stack, but that should be considered an implementation detail.

**Comment by maximecb** [comment]
I added a short document about this and other details: https://github.com/zetavm/zetavm/blob/master/docs/exec_model.md

**Comment by boomshroom** [comment]
Thank you.
