### ISSUE TITLE
Printing arrays

### ISSUE THREAD

**Issue by jammln** [zetavm/zetavm#87]
I attempted to print an array in plush and I get the following error message:
> aborting execution due to error: unhandled type in equality comparison: array

I assume printing arrays isn't implemented in the print function?
An example of this is:
```
var someArray = [1,2,3,5,7];
print(someArray); <--- fails
print(someArray[0]); <--- works fine.
```

**Comment by maximecb** [comment]
The code for the print function would be under `plush/runtime.pls`. It's indeed not implemented right now. Feel free to give it a go if you like :)

**Comment by krypt-n** [comment]
One option would be to add arrays to `string.toString`, since that would be more reusable than an implementation in `print`

**Comment by maximecb** [comment]
@krypt-n That seems like a good idea. We can lazily import `std/string` in the runtime when printing arrays is needed.`

**Comment by maximecb** [comment]
And it's in :)
