### ISSUE TITLE
Timing functions, time library (std/time)

### ISSUE THREAD

**Issue by maximecb** [zetavm/zetavm#97]
In order to do support animations, games, or do benchmarking, we're going to need to support some  timer/timing functions.

Right now, we're limited to 32-bit floats and 32-bit integers, so we can't really do "time since unix epoch", but we could expose a timer function that produces the time since the process started. Because of the limited precision of 32-bit floats, it would probably make the most sense to return this quantity in terms of milliseconds. Future extensions of Zeta, once we have int64 or float64 types, can add more sophisticated timing functions.

AFAIK, the C time functions have terrible precision on windows (less than millisecond), but that could be acceptable for now. Another alternative would be to use performance counters on windows.

Suggestions/feedback on this welcome. Suggestions for other useful time functions also welcome.

**Comment by jammln** [comment]
It would be useful for benchmarking to cancel out the time taken for the VM to load and exit, it would also make repeated benchmarks easier to do as well.

**Comment by maximecb** [comment]
@jammln Not sure how that would be integrated into timing functions.

Timing benchmarks reliably is generally tricky. The way it's typically done is by running the benchmarks a number of time to give the VM some time to "warm up", and then doing a number of timing iterations, and averaging out the times. I would say that this is a separate issue from providing basic general-purpose timing functions though.

**Comment by jammln** [comment]
@maximecb Ah, maybe I miscommunicated, I was just stating a use case and backing up the idea of having timing functions. A millis from start function would be the easiest I think given the 32 bit int limitation.

**Comment by maximecb** [comment]
I implemented a basic `get_time_millis()` function for both Unix and Windows in: https://github.com/zetavm/zetavm/commit/daa45da471bccc498632a1d8390b6a14194c5995
